# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  copyBuilder:
    import: "package:flutter_messages/builder.dart"
    builder_factories: ["wrapperBuilder"]
    build_extensions: {'.arb': ['.flutter.g.dart'], '^pubspec.yaml': []}
    build_to: source
    auto_apply: root_package
    required_inputs: ['.g.dart']