// Generated by flutter_messages.

// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:messages/package_intl_object.dart';

import 'intl_en.g.dart';

class MessagesLocalizations {
  static Iterable<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static LocalizationsDelegate<Messages> delegate =
      MessagesLocalizationsDelegate();

  static List<Locale> get supportedLocales {
    return Messages.knownLocales.map((e) {
      final split = e.split('_');
      final code = split.length > 1 ? split[1] : null;
      return Locale(split.first, code);
    }).toList();
  }

  static Messages? of(BuildContext context) =>
      Localizations.of<Messages>(context, Messages);
}

class MessagesLocalizationsDelegate extends LocalizationsDelegate<Messages> {
  @override
  bool isSupported(Locale locale) =>
      Messages.knownLocales.contains(locale.toString());

  @override
  Future<Messages> load(Locale locale) async {
    await messages.loadLocale(locale.toString());
    return messages;
  }

  @override
  bool shouldReload(LocalizationsDelegate<Messages> old) => false;
}

extension MessagesLocalizationsExtension on BuildContext {
  Messages? get messagesLocalizations => MessagesLocalizations.of(this);
}

Messages messages = Messages(rootBundle.loadString, const OldIntlObject());
